DROP TABLE IF EXISTS person;

CREATE TABLE person(
id SERIAL NOT NULL PRIMARY KEY,
first_name VARCHAR(20) NOT NULL,
last_name VARCHAR(20) NOT NULL,
email VARCHAR(50) NOT NULL UNIQUE,
category VARCHAR(20) NOT NULL
);